[options]
; This sets the directories where Odoo will look for custom and additional addons
; Database connection parameters
db_host = localhost
db_port = 5432
db_user = hmmmm
db_password = Admin123456@
db_name = dbodoo18
; Specifies the HTTP port Odoo will use
http_port = 8069

; The default database Odoo will use
admin_passwd = @Svkbs2024!
addons_path = /Users/hmmmm/odoo/addons,/Users/hmmmm/odoo/custom/